#!/usr/bin/env sh

BUILD_ARGS="-j$(nproc) -Q -s -H /work/hostdir"
BUILD="sudo -Eu builder /work/void-packages/xbps-src $BUILD_ARGS pkg"

COMMAND="
  while IFS= read -r package; do
    echo \"::group::Building \$package...\"
    echo \"$BUILD \$package\"
    $BUILD \$package
    echo \"::endgroup::\"
  done < /work/build-order
"

echo "Running command: $COMMAND"
sh -c "$COMMAND"
